services:
  - type: web
    name: mvp-dataops-docente
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: development
      - key: PORT
        value: "10000"
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_PORT
        value: "5432"
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: SUPABASE_DB_USER
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: MODEL_TARGET_COLUMN
        value: ""
